project:
  type: website
website:
  site-url: https://r-trento.github.io
  title: "R-Trento Users Group"
  description: "R-Trento Users Group"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Please Note** - This site is sill under construction, RTUG has not been launched yet..."
    type: warning
    position: below-navbar
  navbar:
    left:
      - text: "Meetings"
        href: meetings.html
      - text: "Members"
        href: members.html
      - text: "Bibliography"
        href: bibliography.html
      - text: "Contact"
        href: contact.html
    right:
      - icon: github
        href: https://github.com/r-trento
format:
  html:
    toc: true
    anchor-sections: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - custom.scss
    
execute:
  freeze: auto