project:
  type: website
  preview:
    port: 8080
    host: localhost
  resources:
    - "CNAME"
website:
  site-url: https://rtug.unitn.it
  title: "RTUG"
  description: "R-Trento Users Group"
  open-graph: true
  draft-mode: unlinked
  google-analytics: "G-XKT2HCTTXM"
  cookie-consent:
    type: express
    style: simple
    palette: light
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Please Note** - This site is sill under construction, RTUG has not been officially launched yet..."
  #   type: warning
  #   position: below-navbar
  page-footer:
    left: |
      RTUG --- R-Trento Users Group
    center: |
      [Licenses, Logo, and website info](/about.qmd)
    right:
      - icon: github
        href: https://github.com/r-trento
        aria-label: Quarto GitHub
      - icon: rss
        href: index.xml
        aria-label: Quarto Blog RSS
  navbar:
    left:
      - text: "Meetings"
        href: meetings.html
      - text: "Posts"
        href: posts.html
      - text: "Members"
        href: members.html
      - text: "Bibliography"
        href: bibliography.html
      - text: "Contact"
        href: contact.html
    right:
      - icon: info-circle
        href: about.qmd
        text: " "
      - icon: github
        href: https://github.com/r-trento
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/rtug.bsky.social
  # margin-footer: |
  #   :::{.callout-note}
  #   Unless otherwise sepcified, all content is licensed as BY-NC-SA 
  #   [![](https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png){style="margin-top: 10px;"}](https://creativecommons.org/licenses/by-nc-sa/4.0/)
  #   :::
format:
  html:
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - custom.scss
execute:
  freeze: auto
