project:
  type: website
website:
  site-url: https://r-trento.github.io
  title: "R-Trento Users Group"
  description: "R-Trento Users Group"
  navbar:
    left:
      - text: "Meetings"
        href: meetings.html
      - text: "Members"
        href: members.html
      - text: "Bibliography"
        href: bibliography.html
      - text: "Contact"
        href: contact.html
    right:
      - icon: github
        href: https://github.com/r-trento
format:
  html:
    toc: true
    theme: 
      - flatly
      - custom.scss
    
execute:
  freeze: auto